from .jobs_serializer import JobPostingSerializer,JobPostingSerializerListing
from .reg_user_serializer import UserDetailsSerializer,AllUsersDetailsSerializer
from .metadata_serializers import CountryListSerializer,StateListSerializer,DegreeListSerializer,\
    IndustriesListSerializer,SalaryExpectationListSerializer,SkillsListSerializer